# prototype travis setup to exercise "plain old" builds, as well as conda
language: python

matrix:
  include:
    - python: "3.5"
      env: SLICOT_BUILD=conda
    - python: "3.5"
      env: SLICOT_BUILD=plain

before_install:
  - sudo apt-get install gfortran
  - if [[ "$SLICOT_BUILD" == "conda" ]]; then
       ./travis/conda-before_install.sh
    else
       ./travis/plain-before_install.sh
    fi

install:
  - if [[ "$SLICOT_BUILD" == "conda" ]]; then
       ./travis/conda-install.sh
    else
       ./travis/plain-install.sh
    fi

script:
  - if [[ "$SLICOT_BUILD" == "conda" ]]; then
       ./travis/conda-script.sh
    else
       ./travis/plain-script.sh
    fi

after_success:
  - if [[ "$SLICOT_BUILD" == "conda" ]]; then
       ./travis/conda-after_success.sh
    else
       ./travis/plain-after_success.sh
    fi
