# cargo-culted from python-control's .travis.yml
language: python

matrix:
  include:
    - python: "2.7"
      env: SLICOT_BUILD=conda
    - python: "2.7"
      env: SLICOT_BUILD=plain

    - python: "3.3"
      env: SLICOT_BUILD=conda

    - python: "3.4"
      env: SLICOT_BUILD=conda

    - python: "3.5"
      env: SLICOT_BUILD=conda
    - python: "3.5"
      env: SLICOT_BUILD=plain

before_install:
  - sudo apt-get install -qq gfortran
  - if [[ "$SLICOT_BUILD" == "conda" ]]; then
       ./travis/conda-before_install.sh;
    else
       ./travis/plain-before_install.sh;
    fi

install:
  - if [[ "$SLICOT_BUILD" == "conda" ]]; then
       ./travis/conda-install.sh;
    else
       ./travis/plain-install.sh;
    fi

script:
  - if [[ "$SLICOT_BUILD" == "plain" ]]; then
       ./travis/plain-script.sh;
    fi

after_success:
  - if [[ "$SLICOT_BUILD" == "plain" ]]; then
       ./travis/plain-after_success.sh;
    fi
