# appveyor.com continuous integration configuration file
# see https://www.appveyor.com/docs/windows-images-software/#miniconda for pre-installed Miniconda info
# "C:\\Miniconda36-x64\\Scripts" and "C:\\Miniconda36-x64\\Library\\bin" might not be necessary.
install:
  - "set PATH=C:\\Miniconda36-x64;C:\\Miniconda36-x64\\Scripts;C:\\Miniconda36-x64\\Library\\bin;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q --all
  - conda install -q conda-build
  - conda install -q conda-verify
  - conda info -a

build_script: 
  - conda build -c conda-forge conda-recipe-openblas

test_script:
  - cd ..
  - python Slycot/runtests.py --coverage --no-build

  # test with python-control
  - conda install -c conda-forge scipy matplotlib
  - git clone --depth 1 https://github.com/python-control/python-control.git control
  - cd control; python setup.py test
