# appveyor.com continuous integration configuration file
# see https://www.appveyor.com/docs/windows-images-software/#miniconda for pre-installed Miniconda info
# "C:\\Miniconda36-x64\\Scripts" and "C:\\Miniconda36-x64\\Library\\bin" might not be necessary.
platform: x64

environment:
  matrix:
    # - SLYCOT_PYTHON_VERSION: 3.5
    # - SLYCOT_PYTHON_VERSION: 3.6
    - SLYCOT_PYTHON_VERSION: 3.7

install:
  - "set PATH=C:\\Miniconda36-x64;C:\\Miniconda36-x64\\Scripts;C:\\Miniconda36-x64\\Library\\bin;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q --all
  - conda install -q conda-build
  - conda install -q conda-verify
  - conda info -a

build_script: 
  - conda build -c conda-forge --python %SLYCOT_PYTHON_VERSION% conda-recipe-openblas

test_script:
  # force qt version 4 for now; see https://github.com/ContinuumIO/anaconda-issues/issues/1068
  # not quite sure this is the same issue
  - conda create -n test-environment -c conda-forge local::slycot nose
  - activate test-environment

  - python --version

  - cd ..
  - python Slycot/runtests.py --coverage --no-build

  # test with python-control
  - conda install -c conda-forge scipy matplotlib qt=4 numpy>=1.14
  - git clone --depth 1 https://github.com/python-control/python-control.git control
  - cd control
  - python setup.py test
