# appveyor.com continuous integration configuration file
# see https://www.appveyor.com/docs/windows-images-software/#miniconda for pre-installed Miniconda info
# "C:\\Miniconda36-x64\\Scripts" and "C:\\Miniconda36-x64\\Library\\bin" might not be necessary.
install:
  - "set PATH=C:\\Miniconda36-x64;C:\\Miniconda36-x64\\Scripts;C:\\Miniconda36-x64\\Library\\bin;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q --all
  - conda install -q conda-build
  - conda install -q conda-verify
  - conda info -a

build_script: 
  - conda build -c conda-forge conda-recipe-openblas

test_script:
  - conda create -n test-environment
  - activate test-environment
  - conda info -a
  - python -VV
  - python -c "import platform; print(platform.architecture())"
  - which python

  - conda install -c conda-forge local::slycot
  - conda install nose # for tests

  - cd ..
  - python Slycot/runtests.py --coverage --no-build

  # test with python-control
  - conda install -c conda-forge scipy matplotlib
  - git clone --depth 1 https://github.com/roryyorke/python-control.git control
  - cd control
  - git log -1 --pretty=short
  - python setup.py test
