[build-system]
requires = ["scikit-build-core", "numpy", "scipy_openblas32"]
build-backend = "scikit_build_core.build"

[project]
name = "slycot"
dynamic = ["version"]
description = "A wrapper for the SLICOT control and systems library"
readme = "README.rst"
authors = [{ name = "Enrico Avventi et al." }]
maintainers = [{ name = "Slycot developers", email = "python-control-discuss@lists.sourceforge.net"}]
license = "GPL-2.0 AND BSD-3-Clause"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Programming Language :: C",
    "Programming Language :: Fortran",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development",
    "Topic :: Scientific/Engineering",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Operating System :: Unix",
    "Operating System :: MacOS",
]
requires-python = ">=3.10"
dependencies = [
    "numpy",
]

[project.optional-dependencies]
test = ["pytest", "scipy"]

[project.urls]
homepage = "https://github.com/python-control/Slycot"

[tool.scikit-build]
metadata.version.provider = "scikit_build_core.metadata.setuptools_scm"
wheel.exclude = ["slycot/src/", "slycot/CMakeLists.txt", "slycot/slicot-source.cmake", "slycot/scipy-openblas-symbols"]

[tool.pytest.ini_options]
# run the tests with compiled and installed package
addopts = "--pyargs slycot"

[tool.ruff.lint]
ignore = [ "E741" ]

[tool.cibuildwheel]
test-requires = ['pytest', 'scipy']
test-command = "pytest --pyargs slycot"

[tool.cibuildwheel.linux]
repair-wheel-command = [
  "pip install scipy_openblas32",
  "LD_LIBRARY_PATH=$(python -c \"import scipy_openblas32; import os.path; print(scipy_openblas32.get_lib_dir())\")",
  "auditwheel repair -w {dest_dir} {wheel}",
]

[tool.cibuildwheel.windows]
before-build = "pip install delvewheel"
repair-wheel-command = [
  "pip install scipy_openblas32",
  "python tools/delvewheel_wrapper.py repair -w {dest_dir} {wheel}"
]

[tool.cibuildwheel.macos]
repair-wheel-command = "bash {project}/tools/cibw_repair_wheel_macos.sh {dest_dir} {wheel}"
