{% set name = "slycot" %}
{% set version = "0.3.0" %}
{% set variant = "openblas" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 1

requirements:
  build:
    - python
    - openblas
    - numpy
  run:
    - python
    - libgfortran
    - openblas
    - numpy

test:
  imports:
    - slycot

about:
  home: https://github.com/python-control/Slycot
  dev_url: https://github.com/python-control/Slycot
  license: GPL-2.0
  license_family: GPL
  summary: 'Slycot: a wrapper for the SLICOT control and systems library'
  description: |
    Slycot wraps the SLICOT library which is used for control and systems
    analysis.
