package:
  name: slycot
  version: "0.3.2"

# to get test.source_files below to work
source:
  path: ..

build:
  number: 1

  script:
    - cd $RECIPE_DIR/..
    - $PYTHON setup.py install

requirements:
  build:
    - python
    - numpy
    - lapack
    - nose # to force same version of numpy as in test :(

  run:
    - python
    - numpy
    - lapack

test:
  requires:
    - nose # numpy testing requires nose
  source_files:
    - slycot/tests
  commands:
    - python -c "from slycot import tb05ad"
    - python -c "from slycot._wrapper import tb05ad_ng"
    - (cd slycot/tests && python -m unittest discover)

about:
  home: https://github.com/python-control/Slycot
  license:  GPLv2
  summary: 'A wrapper for the SLICOT control and systems library'
