package:
  name: slycot
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'v0.0.0')[1:] }}

source:
  git_url: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{{ environ.get('PY_VER').replace('.', '') }}{{ environ.get('GIT_DESCRIBE_HASH', '') }}_mkl_{{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    
  host:
    - python
    - pip
    - scikit-build
    - numpy
    - libblas
    - libcblas
    - liblapack
    - liblapacke

  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - python
  imports:
    - slycot

about:
  home: https://github.com/python-control/slycot
  license:  GPLv2
  summary: 'A wrapper for the SLICOT control and systems library'
