name: cibuildwheel

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:

      - name: windows-config
        if: startsWith(matrix.os, 'windows')
        run: |
          dir c:\msys64\mingw32\bin\g*.exe
          c:\msys64\mingw32\bin\gcc.exe -v --version
          c:\msys64\mingw32\bin\gfortran.exe -v --version

      # - name: windows-config
      #   if: startsWith(matrix.os, 'windows')
      #   # TODO: equivalent of command -v for gcc, gfortran
      #   # why does CMake find objcopy but not gfortran?  try just "gfortran".
      #   run: |
      #     echo SKBUILD_CMAKE_ARGS="-G Ninja;-DCMAKE_Fortran_COMPILER=c:/msys64/mingw32/bin/gfortran.exe;-DCMAKE_C_COMPILER=c:/msys64/mingw32/bin/gcc.exe" >> $env:GITHUB_ENV

      # - name: Install cibuildwheel
      #   run: python -m pip install cibuildwheel==3.3.1

      # - name: Build wheels
      #   run:  python -m cibuildwheel --output-dir wheelhouse

      # - uses: actions/upload-artifact@v6
      #   with:
      #     name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
      #     path: ./wheelhouse/*.whl
