name: Build and test conda recipe
on:
  push:
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'AUTHORS'
      - 'COPYING'
      - 'gpl-2.0.txt'
      - 'MANIFEST.in'
      - 'README.rst'

jobs:

  build-conda:
    name: Build conda ${{ matrix.config.name }}
    # needs: build-sdist
    strategy:
      fail-fast: true
      matrix:
        config:
          - os: 'windows'
            name: 'Windows 3.14'
            config: 'win_64_python3.14.____cp314'
          - os: 'ubuntu'
            name: 'Linux 3.13'
            config: 'linux_64_python3.13.____cp313.yaml'
    runs-on: ${{ matrix.config.os }}-latest

    env:
      CONFIG: ${{ matrix.config.config }}
      UPLOAD_PACKAGES: 'False'
      UPLOAD_ON_BRANCH: 'False'
      CI: 'github_actions'
      PYTHONUNBUFFERED: 1
      MINIFORGE_HOME: 'c:\\Miniforge'

    steps:
      - name: Checkout Slycot
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Build Windows
        if: startsWith(matrix.config.os, 'windows')
        shell: cmd
        run: |
          call ".scripts\run_win_build.bat"

      - name: Build Linux
        if: startsWith(matrix.config.os, 'ubuntu')
        env:
          GIT_BRANCH: ${{ github.event.workflow_run.head_branch }}
          IS_PR_BUILD: "True"
        run: |
          echo GIT_BRANCH is $GIT_BRANCH
          .scripts/run_docker_build.sh
