name: Build and test conda recipe
on:
  push:
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'AUTHORS'
      - 'COPYING'
      - 'gpl-2.0.txt'
      - 'MANIFEST.in'
      - 'README.rst'

jobs:

  build-conda:
    name: Build conda, ${{ matrix.os }} ${{ matrix.python }}
    runs-on: ${{ matrix.os }}-latest
    # needs: build-sdist
    strategy:
        fail-fast: false
        matrix:
          os:
            - 'windows'
          python:
            - '3.14'

    env:
      CONFIG: 'win_64_python3.14.__cp314'
      UPLOAD_PACKAGES: 'False'
      UPLOAD_ON_BRANCH: 'False'
      CI: 'github_actions'
      PYTHONUNBUFFERED: 1
      MINIFORGE_HOME: 'c:\\Miniforge'

    steps:
      - name: Checkout Slycot
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Build
        run: |
          call ".scripts\run_win_build.bat"
