name: Conda build

on:
  push:
  pull_request:

jobs:

  build-conda:
    name: Build conda, ${{ matrix.os }} ${{ matrix.python }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
        matrix:
          os:
            - 'windows'
          python:
            - '3.13'

    steps:
      - name: Checkout Slycot
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python }}
          activate-environment: build-env
          miniforge-version: latest
          conda-build-version: 26.3.0
          channel-priority: strict
      - name: Conda build
        shell: bash -el {0}
        env:
          SKBUILD_CMAKE_ARGS: "-G Ninja"
        run: |
          set -ex
          echo $SKBUILD_CMAKE_ARGS
          conda build conda-recipe --python ${{ matrix.python }}
          # preserve directory structure for custom conda channel
          CONDA_ROOT=$(conda info --base)
          find "${CONDA_ROOT}/conda-bld" -maxdepth 2 -name 'slycot*.conda' | while read -r conda_pkg; do
            conda_platform=$(basename $(dirname "${conda_pkg}"))
            mkdir -p "slycot-conda-pkgs/${conda_platform}"
            cp "${conda_pkg}" "slycot-conda-pkgs/${conda_platform}/"
          done
          conda index ./slycot-conda-pkgs
