name: Build and Test Slycot
on:
  push:
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'AUTHORS'
      - 'COPYING'
      - 'gpl-2.0.txt'
      - 'MANIFEST.in'
      - 'README.rst'

jobs:

  build-conda:
    name: Build conda, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
        fail-fast: false
        matrix:
          os:
            - 'ubuntu'
            - 'macos'
            - 'windows'
          python:
            - '3.10'
            - '3.13'

    steps:
      - name: Checkout Slycot
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python }}
          activate-environment: build-env
          miniforge-version: latest
          conda-build-version: 25.7.0
          channel-priority: strict
      - name: Conda build
        run: |
          conda build conda-recipe --numpy 2 --python ${{ matrix.python }}
