name: Build and Test Slycot
on:
  push:
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'AUTHORS'
      - 'COPYING'
      - 'gpl-2.0.txt'
      - 'MANIFEST.in'
      - 'README.rst'

jobs:

  build-conda:
    name: Build conda, ${{ matrix.os }} ${{ matrix.python }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
        fail-fast: false
        matrix:
          os:
            - 'ubuntu'
            # - 'macos'
            # - 'windows'
          python:
            - '3.13'

    steps:
      - name: Checkout Slycot
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python }}
          activate-environment: build-env
          miniforge-version: latest
          conda-build-version: 25.7.0
          channel-priority: strict
      - name: Conda build
        shell: bash -el {0}
        run: |
          set -e
          conda build conda-recipe --python ${{ matrix.python }}
          # preserve directory structure for custom conda channel
          CONDA_ROOT=$(conda info --base)
          find "${CONDA_ROOT}/conda-bld" -maxdepth 2 -name 'slycot*.conda' | while read -r conda_pkg; do
            conda_platform=$(basename $(dirname "${conda_pkg}"))
            mkdir -p "slycot-conda-pkgs/${conda_platform}"
            cp "${conda_pkg}" "slycot-conda-pkgs/${conda_platform}/"
          done
          conda index ./slycot-conda-pkgs
      - name: Save to local conda pkg channel
        uses: actions/upload-artifact@v4
        with:
          name: slycot-conda-pkgs-${{ matrix.os }}-${{ matrix.python }}
          path: slycot-conda-pkgs
          retention-days: 5


  create-conda-test-matrix:
    name: Create conda test matrix
    runs-on: ubuntu-latest
    needs: build-conda
    if: always()  # run tests for all successful builds, even if others failed
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Merge artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: slycot-conda-pkgs
          pattern: slycot-conda-pkgs-*
      - name: Checkout Slycot
        uses: actions/checkout@v3
      - name: Download conda packages
        uses: actions/download-artifact@v4
        with:
          name: slycot-conda-pkgs
          path: slycot-conda-pkgs
      - id: set-matrix
        run: |
          TEMPFILE="$(mktemp)"
          python3 .github/scripts/set-conda-test-matrix.py | tee $TEMPFILE
          echo "matrix=$(cat $TEMPFILE)" >> $GITHUB_OUTPUT


  test-conda:
    name: Test conda ${{ matrix.packagekey }}, ${{matrix.blas_lib}} BLAS lib ${{ matrix.failok }}
    needs: create-conda-test-matrix
    runs-on: ${{ matrix.os }}-latest
    continue-on-error: ${{ matrix.failok == 'FAILOK' }}

    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.create-conda-test-matrix.outputs.matrix) }}

    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout Slycot
        uses: actions/checkout@v3
        with:
          path: slycot-src
      - name: Checkout python-control
        uses: actions/checkout@v3
        with:
          repository: 'python-control/python-control'
          path: python-control
      - name: Setup macOS
        if: matrix.os == 'macos'
        run: brew install coreutils
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python }}
          miniforge-version: latest
          activate-environment: test-env
          environment-file: slycot-src/.github/conda-env/test-env.yml
          channels: conda-forge,defaults
          channel-priority: strict
          auto-activate-base: false
      - name: Download conda packages
        uses: actions/download-artifact@v4
        with:
          name: slycot-conda-pkgs
          path: slycot-conda-pkgs
      - name: Install Conda package
        run: |
          set -e
          case ${{ matrix.blas_lib }} in
            unset        ) # the conda-forge default (os dependent)
              conda install libblas libcblas liblapack
              ;;
            Generic      )
              conda install 'libblas=*=*netlib' 'libcblas=*=*netlib' 'liblapack=*=*netlib'
              echo "libblas * *netlib" >> $CONDA_PREFIX/conda-meta/pinned
              ;;
            OpenBLAS     )
              conda install 'libblas=*=*openblas' openblas
              echo "libblas * *openblas" >> $CONDA_PREFIX/conda-meta/pinned
              ;;
            Intel10_64lp )
              conda install 'libblas=*=*mkl' mkl
              echo "libblas * *mkl" >> $CONDA_PREFIX/conda-meta/pinned
              ;;
          esac
          conda install -c ./slycot-conda-pkgs slycot
          conda list
      - name: Slycot and python-control tests
        run: JOBNAME="$JOBNAME" bash -el slycot-src/.github/scripts/run-tests.sh
        env:
          JOBNAME: conda ${{ matrix.packagekey }} ${{ matrix.blas_lib }}
      - name: report coverage
        uses: coverallsapp/github-action@v2
        with:
          flag-name: wheel-${{ matrix.packagekey }}-${{matrix.blas_lib}}
          parallel: true
          file: slycot-src/coverage.xml
