name: Build and Test Slycot
on:
  push:
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'AUTHORS'
      - 'COPYING'
      - 'gpl-2.0.txt'
      - 'MANIFEST.in'
      - 'README.rst'

jobs:

  build:
    name: Build ${{ matrix.os }} ${{ matrix.python }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
        fail-fast: false
        matrix:
          os:
            - 'windows'
          python:
            - '3.13'

    steps:
      - name: Install OpenBLAS
        run: |
          curl.exe --verbose --location https://github.com/OpenMathLib/OpenBLAS/releases/download/v0.3.30/OpenBLAS-0.3.30-x64.zip --output OpenBLAS-0.3.30-x64.zip
          mkdir /OpenBLAS-0.3.30
          unzip OpenBLAS-0.3.30-x64.zip -d /OpenBLAS-0.3.30

      - name: Checkout Slycot
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: gcc
          version: 'latest'


      - name: install python-build
        run: pip install build
      - name: build
        run: |
          python -m build "--config-setting=cmake.args=-G Ninja"\
              "--config-setting=cmake.args=-DCMAKE_MODULE_PATH=/OpenBLAS-0.3.30/lib/cmake/openblas"\
              "-DBLA_VENDOR=OpenBLAS"
